### ISSUE TITLE
How to convert UFF model into TensorRT engines

### ISSUE THREAD

**Issue by surajmahangade** [CnnDepth/tx2_fcnn_node#12]
I checked the https://github.com/CnnDepth/tensorrt_samples/tree/master/sampleUffFCRN
But i am not able to understand how do i run it.
How to build that project and run it exactly?
Thank you

**Comment by avbokovoy** [comment]
You can build the engine using tx2_fcnn_node. Check "Compile the engine" in the [Compile](https://github.com/CnnDepth/tx2_fcnn_node#compile) section. Building the engine with sampleUffFCRN is outdated.

**Comment by surajmahangade** [comment]
Thank you for a prompt reply.
I ran it and when i rosrun the command I get segmentation fault.
But everything else works.Hope that won't make a problem .
The depth map i am getting is not that great.
Is there anything to be changed for better depth map.
My image is calibrated.

**Comment by avbokovoy** [comment]
Yes, segmentation fault sometimes occurs, but the engine should compile anyway.
It's hard to estimate what do you actually mean by "not that great". The overall quality depends on several parameters: 
1) Camera quality. 
2) The environment you are operating in. The deep learning approaches in depth reconstruction are not an universal solution. The environment should look similar to the training data, e.g. NYU Dataset v2. So the neural network's quality is better indoor, then outdoor, camera should be on ~1m height and etc. 
3) The data formats. Make sure you pass the image in right color scheme.

**Comment by surajmahangade** [comment]
Okay I will check all those things.
Is there any benchmark of all the pre-trained model given by you.
Thank you.

**Comment by KirillMouraviev** [comment]
The output name for `resnet_interleaving_2shortcuts_640x480` model is `tf/reshape_1/Reshape`. To build engine from this model, use following command:
`rosrun tx2_fcnn_node fcrn_engine_builder --uff=./resnet_interleaving_2shortcuts_640x480.uff --uffInput=tf/Placeholder --output=tf/reshape_1/Reshape --height=480 --width=640 --engine=./test_engine.trt --fp16`

**Comment by surajmahangade** [comment]
Yeah that worked.
Thank you
