### ISSUE TITLE
Using 640 X 480 uff file

### ISSUE THREAD

**Issue by rahulmoorthy19** [CnnDepth/tx2_fcnn_node#14]
Hello,

Firstly thank you for such a great implementation for converting 2d image to depth image. I had one issue..so with 320 X 240. Everything is working great but now I am shifting to 640 X 480 for better map building. I am facing one issue while going through the conversion process..
1. I used the following command to get the .test_engine of 640 X 480
              rosrun tx2_fcnn_node fcrn_engine_builder --uff=./resnet_nonbt_shortcuts_640x480.uff --uffInput=tf/Placeholder --output=tf/reshape_1/Reshape --height=480 --width=640 --engine=./test_engine.trt --fp16

2. I changed the values in the launch file. The cnn_only launch file is added to the issue
[cnn_only.txt](https://github.com/CnnDepth/tx2_fcnn_node/files/5253886/cnn_only.txt)

3. I also changed the height and width values in the camera calibration file. I have add the file to the issue.
[tx2_camera_calib.txt](https://github.com/CnnDepth/tx2_fcnn_node/files/5253890/tx2_camera_calib.txt)

Now when I create a Rtabmap using this. I get the following error.

terminate called after throwing an instance of 'UException'
  what():  [FATAL] (2020-09-21 12:35:45.125) util3d_features.cpp:92::generateKeypoints3DDepth() Condition (cameraIndex >= 0 && cameraIndex < (int)cameraModels.size()) not met! [cameraIndex=1, models=1, kpt.x=540.000000, subImageWidth=640.000000 (Camera model image width=320)]

Is there anything else which needs to be changed except the above changes to make this work?

Thanking you in advance

**Comment by avbokovoy** [comment]
Hello,

Sorry for the late response. I've inspected your tx2_camera_calib.txt file and noticed, that you forgot to change resolution (image_width, image_height parameters). Since your issue is resolution mismatch in RTAB-Map, and this parameters affect camera_info topic, that RTAB-Map uses for image processing, that should help.

**Comment by rahulmoorthy19** [comment]
Sorry I did not send the updated file. I did update the width and height parameters and got the same error. Is there any place else I need to do some change too

**Comment by avbokovoy** [comment]
Have you tried rtabmap_cnn.launch file with corrected height/width parameters? If not, what parameters do you use when you launch RTAB-Map? 

I've just tested RTAB-Map + tx2_fcnn_node with 640x480 engine and web-camera with no issue. What do you use as an input?

**Comment by rahulmoorthy19** [comment]
Got the issue...Thank You for the help
