### ISSUE TITLE
Thirdparty/fcrn-inference does not contain a CMakeLists.txt file

### ISSUE THREAD

**Issue by IbrahimOmar91** [CnnDepth/tx2_fcnn_node#6]
I’m having this error 
`
CMake Error at tx2_fcnn_node/CMakeLists.txt:10 (add_subdirectory):
  The source directory
    /home/carkyo/catkin_ws/src/tx2_fcnn_node/Thirdparty/fcrn-inference
  does not contain a CMakeLists.txt file.
`

I'm using:
Ubuntu: 16.04
ROS: Kinetic
CUDA: 9.0
cudnn: 7.6

Full Terminal Output
[Base path: /home/carkyo/catkin_ws
Source space: /home/carkyo/catkin_ws/src
Build space: /home/carkyo/catkin_ws/build
Devel space: /home/carkyo/catkin_ws/devel
Install space: /home/carkyo/catkin_ws/install

 Running command: "cmake /home/carkyo/catkin_ws/src -DCATKIN_DEVEL_PREFIX=/home/carkyo/catkin_ws/devel -DCMAKE_INSTALL_PREFIX=/home/carkyo/catkin_ws/install -G Unix Makefiles" in "/home/carkyo/catkin_ws/build"

-- Using CATKIN_DEVEL_PREFIX: /home/carkyo/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/kinetic
-- This workspace overlays: /opt/ros/kinetic
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/carkyo/catkin_ws/build/test_results
-- Found gmock sources under '/usr/src/gmock': gmock will be built
-- Found gtest sources under '/usr/src/gmock': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.18
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 1 packages in topological order:
-- ~~  - tx2_fcnn_node
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'tx2_fcnn_node'
-- ==> add_subdirectory(tx2_fcnn_node)
CMake Error at tx2_fcnn_node/CMakeLists.txt:10 (add_subdirectory):
  The source directory
    /home/carkyo/catkin_ws/src/tx2_fcnn_node/Thirdparty/fcrn-inference
  does not contain a CMakeLists.txt file.

TensorRT libraries path: /home/carkyo/Downloads/TensorRT-5.1.5.0/lib
TensorRT includes path: /home/carkyo/Downloads/TensorRT-5.1.5.0/include
CuDNN found in /usr/local/cuda/lib64
CuBLAS found in /usr/local/cuda/lib64
CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:166 (message):
  catkin_package() DEPENDS on 'system_lib' but neither
  'system_lib_INCLUDE_DIRS' nor 'system_lib_LIBRARIES' is defined.
Call Stack (most recent call first):
  /opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)
  tx2_fcnn_node/CMakeLists.txt:157 (catkin_package)

-- dir='/home/carkyo/catkin_ws/src/tx2_fcnn_node/include'
-- dir='/opt/ros/kinetic/include'
-- dir='/opt/ros/kinetic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp'
-- dir='/opt/ros/kinetic/include/opencv-3.3.1-dev'
-- dir='/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv'
-- dir='/usr/include'
-- dir='/opt/ros/kinetic/include/opencv-3.3.1-dev'
-- dir='/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv'
-- dir='/usr/local/cuda/include'
-- dir='/home/carkyo/catkin_ws/build/tx2_fcnn_node/Thirdparty/fcrn-inference/x86_64/include'
-- dir='/include'
-- dir='/usr/lib/x86_64-linux-gnu/gstreamer-1.0'
-- dir='/usr/lib/x86_64-linux-gnu/gstreamer-1.0/include'
-- dir='/usr/lib/aarch64-linux-gnu/gstreamer-1.0/include'
-- dir='/usr/include/gstreamer-1.0'
-- dir='/usr/lib/aarch64-linux-gnu/gstreamer-1.0/include'
-- dir='/usr/include/glib-2.0'
-- dir='/usr/lib/x86_64-linux-gnu/glib-2.0/include'
-- dir='/usr/lib/aarch64-linux-gnu/glib-2.0/include'
-- dir='/home/carkyo/Downloads/TensorRT-5.1.5.0/include'
-- Configuring incomplete, errors occurred!
See also "/home/carkyo/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/carkyo/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed]

**Comment by avbokovoy** [comment]
Most likely the fcrn-inference submodule is missing. Try to run
```bash
git submodule update --init --recursive
```
in project's root folder.

**Comment by IbrahimOmar91** [comment]
> Most likely the fcrn-inference submodule is missing. Try to run
> 
> ```shell
> git submodule update --init --recursive
> ```
> 
> in project's root folder.

Thank You, this solved the problem
but when i try to run the node using `roslaunch tx2_fcnn_node cnn_only.launch` I get this error 
[cnn_only.launch] is neither a launch file in package [tx2_fcnn_node] nor is [tx2_fcnn_node] a launch file name
The traceback for the exception was written to the log file

**Comment by avbokovoy** [comment]
You need to compile the engine first with uff model. This needs a better clarification in future version of README. See https://github.com/CnnDepth/tx2_fcnn_node/blob/master/README.md#sample-models

**Comment by avbokovoy** [comment]
Closing this issue due to now updates. If you still have the problem, feel free to reopen.
