### ISSUE TITLE
Questione about mapping

### ISSUE THREAD

**Issue by viet2411** [CnnDepth/tx2_fcnn_node#9]
Hello, 
I'm planning to do navigation by octomap using your research and I was wondering if we can generate an octomap in the same time with the point cloud map. 
Thank you and best regards.

**Comment by avbokovoy** [comment]
Hello!

Sure, the point cloud and octomap are published by RTAB-MAP ROS node to /cloud_map and /octomap_full topics respectively.

**Comment by viet2411** [comment]
Thank you!
Have you tested this on an outdoor environment yet?

**Comment by avbokovoy** [comment]
We haven't tested it in outdoor environment yet. Our models may not work as expected in this case, because they were trained on NYU Dataset v2, which contains the image-depth pairs from indoor environment. However, you never know unless you try :)

**Comment by viet2411** [comment]
Thank you. I'm considering on retraining your network on an outdoor environment with depth map (eg. KITTI dataset) and testing it accuracy.
By the way, can RTAB map export octomap? I can't see this in your code (sorry for the question, I'm totally new in ROS)

**Comment by avbokovoy** [comment]
Sounds cool! Would be nice to see your results.

I'm not sure about octomaps, but you can export pointcloud with [pcl_ros](http://wiki.ros.org/pcl_ros#pointcloud_to_pcd) and produce the octomap from exported pointcloud.

**Comment by avbokovoy** [comment]
Closing this issue due to now updates. If you still have the problem, feel free to reopen.
